server:
  port: 9030
  servlet:
    context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: deepseek/deepseek-v4-flash
          temperature: 0.0
