server:
  port: 9030
  servlet:
    context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  # ai:
  #   openai:
  #     api-key: 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
  #     base-url: https://openrouter.ai/api
  #     chat:
  #       options:
  #         model: openai/gpt-5.5
  #         temperature: 0.0
  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: anthropic/claude-haiku-4.5
          temperature: 0.0

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/intelligence_db
    username: intelligence_user
    password: ${DB_PASSWORD}

ai:
    model.chat: openai
    openai:
      api-key: ${AI_API_KEY}
    chat:
        options:
          model: anthropic/claude-haiku-4.5
